export const ROUTES = {
  HOME: "/",
  AUTH: "/auth",
  FEATURES: "/features",
  TERMS_OF_USE: "/terms-of-use",
  PRIVACY_POLICY: "/privacy-policy",
  APP: "/app",
  VIDEO_MAKER: "/app/video-maker",
  HELP_CENTER: "/help-center",
  ABOUT_US: "/about-us",
  DASHBOARD: "/app",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  UPGRADE: "/upgrade",
  NOT_FOUND: "*",
  PRICING: "/pricing",
  PRICING_SUCCESS: "/payment/success",
};
